smartpca -i /home1/mkato/hdd_data/data/1-withAADR/1-0-merged_eigen/jomon_aadr_jomon_down.geno \
-a /home1/mkato/hdd_data/data/1-withAADR/1-0-merged_eigen/jomon_aadr_jomon_down.snp \
-b /home1/mkato/hdd_data/data/1-withAADR/1-0-merged_eigen/jomon_aadr_jomon_down.ind \
-k 4 \
-o /home1/mkato/hdd_data/data/1-withAADR/1-1-pca/jomon_aadr_asia_jomon_down.evec.txt \
-p /home1/mkato/hdd_data/data/1-withAADR/1-1-pca/jomon_aadr_asia_jomon_down.plot.txt \
-e /home1/mkato/hdd_data/data/1-withAADR/1-1-pca/jomon_aadr_asia_jomon_down.eval.txt \
-l /home1/mkato/hdd_data/data/1-withAADR/1-1-pca/jomon_aadr_asia_jomon_down.log \
-m 0 \
-t 10 \
-w /home/mkato/hdd_data/data/1-withAADR/1-0-merged_eigen/asia_poplist.txt \
