smartpca -i /home1/mkato/hdd_data/data/1-withAADR/1-0-merged_eigen/jomon_aadr.geno \
-a /home1/mkato/hdd_data/data/1-withAADR/1-0-merged_eigen/jomon_aadr.snp \
-b /home1/mkato/hdd_data/data/1-withAADR/1-0-merged_eigen/jomon_aadr.ind \
-o /home1/mkato/hdd_data/data/1-withAADR/1-1-pca/present.evec.txt \
-p /home1/mkato/hdd_data/data/1-withAADR/1-1-pca/present.plot.txt \
-e /home1/mkato/hdd_data/data/1-withAADR/1-1-pca/present.eval.txt \
-l /home1/mkato/hdd_data/data/1-withAADR/1-1-pca/present.log \
-m 0 \
-k 4 \
-m 0 \
-t 10 \
-w /home/mkato/hdd_data/data/1-withAADR/1-0-merged_eigen/present_poplist.txt \
